config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :students
      resources :semesters
    end
  end
  # resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/semester.rb
class Semester < ApplicationRecord
	has_many :students, dependent: :destroy
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :semester
end

app/controllers/api/v1/semesters_controller.rb
class Api::V1::SemestersController < ApplicationController
	before_action :set_semester, only: [:show, :edit, :update, :destroy]

  # GET http://localhost:3000/api/v1/semesters
  def index
    @semesters = Semester.all
    render json: @semesters
  end

  # GET http://localhost:3000/api/v1/semesters/1
  def show
  	render json: @semester
  end

  def new
    @semester = Semester.new
  end

  def edit
  end

  # PUT http://localhost:3000/api/v1/semesters?semester[name]=student semester&semester[credits]=1&semester[start_date]=2019-01-19&semester[end_date]=2019-06-19
  def create
    @semester = Semester.new(semester_params)
    if @semester.save
    	render json: @semester 
  	else
    	render json: @semester.errors, status: :unprocessable_entity 
  	end
  end

  # PATCH http://localhost:3000/api/v1/semesters/2?semester[name]=student semester
  def update
    if @semester.update(semester_params)
     	render json: @semester 
  	else
    	render json: @semester.errors, status: :unprocessable_entity 
  	end
  end

  # DELETE http://localhost:3000/api/v1/semesters/2
  def destroy
    @semester.destroy
    head :no_content
  end

  private
    def set_semester
      @semester = Semester.find(params[:id])
    end

    def semester_params
      params.require(:semester).permit(:name, :credits, :start_date, :end_date)
    end
end

app/controllers/api/v1/students_controller.rb
class Api::V1::StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  
  # GET http://localhost:3000/api/v1/students
  def index
    @students = Student.all
    render json: @students
  end

  # GET http://localhost:3000/api/v1/students/1
  def show
    render json: @student
  end

  def new
    @student = Student.new
  end

  def edit
  end

  # # PUT http://localhost:3000/api/v1/students?student[name]=student_name&student[age]=1&student[bod]=2019-01-01&semester_id=1
  def create
    @student = Student.new(student_params)
    if @student.save
      render json: @student 
    else
      render json: @student.errors, status: :unprocessable_entity 
    end
  end

  # PATCH http://localhost:3000/api/v1/students/3?student[name]=student_new_name
  def update
    if @student.update(student_params)
      render json: @student 
    else
      render json: @student.errors, status: :unprocessable_entity 
    end
  end

  # DELETE http://localhost:3000/api/v1/students/2
  def destroy
    @student.destroy
    head :no_content
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name,:age,:bod,:description,:semester_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  # ActionController::Base
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: [:show, :edit, :update, :destroy]

  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      params.require(:semester).permit(:name, :credits, :start_date, :end_date)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name)
    end
end

app/helpers/api/v1/semester_helper.rb
module Api::V1::SemesterHelper
end

app/helpers/api/v1/semesters_helper.rb
module Api::V1::SemestersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/semesters/_form.html.erb
<%= form_with(model: semester, local: true) do |form| %>
  <% if semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :credits %>
    <%= form.text_field :credits %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>Editing Semester</h1>

<%= render 'form', semester: @semester %>

<%= link_to 'Show', @semester %> |
<%= link_to 'Back', semesters_path %>

app/views/semesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Semesters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Credits</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.name %></td>
        <td><%= semester.credits %></td>
        <td><%= semester.start_date %></td>
        <td><%= semester.end_date %></td>
        <td><%= link_to 'Show', semester %></td>
        <td><%= link_to 'Edit', edit_semester_path(semester) %></td>
        <td><%= link_to 'Destroy', semester, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semester', new_semester_path %>

app/views/semesters/new.html.erb
<h1>New Semester</h1>

<%= render 'form', semester: @semester %>

<%= link_to 'Back', semesters_path %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @semester.name %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @semester.credits %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @semester.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @semester.end_date %>
</p>

<%= link_to 'Edit', edit_semester_path(@semester) %> |
<%= link_to 'Back', semesters_path %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>